# Generated by Django 5.0.4 on 2024-05-30 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('contenu', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
