# Generated by Django 5.0.4 on 2024-05-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test_field2',
        ),
    ]
